### ISSUE TITLE
Test duration

### ISSUE THREAD

**Issue by steveb369** [olib963/javatest#33]
**New Feature**
**As a** Javatest tester **I want** to see the test duration logged for each test **so that** I can determine test performance over time.

Just thought it would be nice to have test run times, maybe even aggregated totals too?

**Comment by olib963** [comment]
I am going to mark this one as complete for now. This is included in version 0.2.0+. Aggregation of data is something I would like to handle in a typesafe way in the future when I have a few more pieces of "context" data that can be added to tests.

Currently you can benchmark an individual test or whole test run. You can also fail tests if they take too long.
